import { describe, it, expect } from 'vitest'
import { generateReport } from './reporter.js'
import type { AnalysisContext, LLMOutput } from './types.js'

const ctx: AnalysisContext = {
  git: {
    baseBranch: 'main',
    headBranch: 'feat/login',
    changedFiles: [],
    stats: { additions: 50, deletions: 10, filesChanged: 3 },
    commits: [],
  },
  dependencies: { impactedFiles: [], sharedModules: [], entryPoints: [] },
  history: {
    hotspots: [
      { path: 'src/auth.ts', commitCount: 12, fixCount: 4, riskLevel: 'high' },
    ],
    recentFixCommits: [],
  },
  testCoverage: {
    covered: [],
    uncovered: ['src/auth.ts'],
    relatedTests: [],
    coverageRatio: 0,
  },
  stageWarnings: [],
}

const llmResult: LLMOutput = {
  summary: '本次变更涉及认证模块，风险较高',
  riskLevel: 'high',
  checklist: [
    {
      id: 'CHK-001',
      priority: 'critical',
      category: '安全',
      title: '检查 token 过期处理',
      description: '验证 token 过期后是否正确跳转登录页',
      relatedFiles: ['src/auth.ts'],
      verificationMethod: 'manual',
    },
    {
      id: 'CHK-002',
      priority: 'low',
      category: '性能',
      title: '检查缓存策略',
      description: '确认用户信息缓存在 token 刷新后被清除',
      relatedFiles: [],
      verificationMethod: 'unit-test',
    },
  ],
  testSuggestions: [
    { type: 'existing', path: 'src/__tests__/auth.test.ts', description: '运行认证测试', reason: '直接覆盖变更' },
    { type: 'new', description: '新增 token 过期测试', reason: '现有测试未覆盖过期场景' },
  ],
  warnings: ['注意：认证模块修改需要安全审查'],
}

describe('generateReport', () => {
  const report = generateReport(ctx, llmResult)

  it('includes header with branch info', () => {
    expect(report).toContain('feat/login')
    expect(report).toContain('main')
    expect(report).toContain('HIGH')
  })

  it('includes summary', () => {
    expect(report).toContain('本次变更涉及认证模块')
  })

  it('includes checklist grouped by priority', () => {
    expect(report).toContain('Critical')
    expect(report).toContain('CHK-001')
    expect(report).toContain('Low')
    expect(report).toContain('CHK-002')
  })

  it('includes test suggestions', () => {
    expect(report).toContain('建议运行的已有测试')
    expect(report).toContain('建议新增的测试')
    expect(report).toContain('token 过期测试')
  })

  it('includes risk hotspots table', () => {
    expect(report).toContain('风险热区')
    expect(report).toContain('src/auth.ts')
    expect(report).toContain('12 次')
  })

  it('includes coverage gaps', () => {
    expect(report).toContain('测试覆盖缺口')
    expect(report).toContain('src/auth.ts')
  })

  it('includes warnings', () => {
    expect(report).toContain('注意事项')
    expect(report).toContain('安全审查')
  })

  it('includes footer with timestamp', () => {
    expect(report).toContain('Generated by TestMind')
  })

  it('includes stage warnings when present', () => {
    const ctxWithWarnings = { ...ctx, stageWarnings: ['[依赖追踪] 分析失败，数据可能不完整: git error'] }
    const r = generateReport(ctxWithWarnings, llmResult)
    expect(r).toContain('数据完整性警告')
    expect(r).toContain('依赖追踪')
  })
})
