import type { AnalysisContext, LLMOutput } from './types.js'

const RISK_EMOJI: Record<string, string> = { high: 'HIGH', medium: 'MEDIUM', low: 'LOW' }
const PRIORITY_ORDER = ['critical', 'high', 'medium', 'low'] as const

export function generateReport(ctx: AnalysisContext, llmResult: LLMOutput): string {
  const { git, history, testCoverage } = ctx
  const lines: string[] = []

  // Header
  lines.push('# TestMind 自测检查清单')
  lines.push('')
  lines.push(
    `> 分支: ${git.headBranch} → ${git.baseBranch} | ` +
    `变更: ${git.stats.filesChanged} files (+${git.stats.additions} -${git.stats.deletions}) | ` +
    `风险等级: **${RISK_EMOJI[llmResult.riskLevel]}**`,
  )
  lines.push('')

  // Summary
  lines.push('## 概要')
  lines.push('')
  lines.push(llmResult.summary)
  lines.push('')

  // Checklist grouped by priority
  if (llmResult.checklist.length > 0) {
    lines.push('## 检查清单')
    lines.push('')

    for (const priority of PRIORITY_ORDER) {
      const items = llmResult.checklist.filter(c => c.priority === priority)
      if (items.length === 0) continue

      lines.push(`### ${priority.charAt(0).toUpperCase() + priority.slice(1)}`)
      lines.push('')
      for (const item of items) {
        lines.push(`- [ ] **${item.id}** [${item.category}] ${item.title}`)
        lines.push(`  - ${item.description}`)
        if (item.relatedFiles.length > 0) {
          lines.push(`  - 文件: ${item.relatedFiles.map(f => `\`${f}\``).join(', ')}`)
        }
        lines.push(`  - 验证方式: ${item.verificationMethod}`)
        lines.push('')
      }
    }
  }

  // Test suggestions
  const existing = llmResult.testSuggestions.filter(t => t.type === 'existing')
  const newTests = llmResult.testSuggestions.filter(t => t.type === 'new')

  if (existing.length > 0 || newTests.length > 0) {
    lines.push('## 测试建议')
    lines.push('')

    if (existing.length > 0) {
      lines.push('### 建议运行的已有测试')
      lines.push('')
      for (const t of existing) {
        lines.push(`- \`${t.path}\` — ${t.description}`)
        lines.push(`  - 原因: ${t.reason}`)
      }
      lines.push('')
    }

    if (newTests.length > 0) {
      lines.push('### 建议新增的测试')
      lines.push('')
      for (const t of newTests) {
        lines.push(`- ${t.description}`)
        lines.push(`  - 原因: ${t.reason}`)
      }
      lines.push('')
    }
  }

  // Risk hotspots
  const riskyHotspots = history.hotspots.filter(h => h.riskLevel !== 'low')
  if (riskyHotspots.length > 0) {
    lines.push('## 风险热区')
    lines.push('')
    lines.push('| 文件 | 近 90 天修改 | Bug 修复 | 风险 |')
    lines.push('|------|-------------|---------|------|')
    for (const h of riskyHotspots) {
      lines.push(`| \`${h.path}\` | ${h.commitCount} 次 | ${h.fixCount} 次 | ${h.riskLevel.toUpperCase()} |`)
    }
    lines.push('')
  }

  // Test coverage gaps
  if (testCoverage.uncovered.length > 0) {
    lines.push('## 测试覆盖缺口')
    lines.push('')
    lines.push('以下变更文件没有找到对应测试:')
    lines.push('')
    for (const p of testCoverage.uncovered) {
      lines.push(`- \`${p}\``)
    }
    lines.push('')
  }

  // Stage warnings
  if (ctx.stageWarnings && ctx.stageWarnings.length > 0) {
    lines.push('## 数据完整性警告')
    lines.push('')
    lines.push('> 以下分析阶段出现问题，报告数据可能不完整：')
    lines.push('')
    for (const w of ctx.stageWarnings) {
      lines.push(`- ${w}`)
    }
    lines.push('')
  }

  // Warnings
  if (llmResult.warnings.length > 0) {
    lines.push('## 注意事项')
    lines.push('')
    for (const w of llmResult.warnings) {
      lines.push(`- ${w}`)
    }
    lines.push('')
  }

  // Footer
  lines.push('---')
  lines.push(`Generated by TestMind MVP-0 | ${new Date().toISOString().replace('T', ' ').slice(0, 19)}`)
  lines.push('')

  return lines.join('\n')
}
